version: '2'
services:
  app:
    build: .
    image: ruby:2.2
    entrypoint: bin/entrypoint
    volumes:
      - .:/app
      - bundle:/bundle
    depends_on:
      - elasticsearch
    command: ["./bin/wait-for-it.sh", "elasticsearch:9200", "--", "bundle", "exec", "rspec"]

  elasticsearch:
    image: elasticsearch:5.2
    ports:
      - '9200:9200'

volumes:
  bundle:
